config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :kitaps, :path =>"kitaplar" do
	  	resources :yorums, :path =>"yorumlar"
	    put "like", to: "kitaps#like"
  end
  resources :yazars
  root "kitaps#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitap.rb
class Kitap < ApplicationRecord
	has_attached_file :resim, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :resim, content_type: /\Aimage\/.*\z/
 	belongs_to :user
 	has_many :yorums
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :kitaps
  has_many :yorums
end

app/models/yazar.rb
class Yazar < ApplicationRecord
end

app/models/yorum.rb
class Yorum < ApplicationRecord
	belongs_to :kitap
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kitaps_controller.rb
class KitapsController < ApplicationController
  before_action :set_kitap, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]

  # GET /kitaps
  # GET /kitaps.json
  def index
    @kitaps = Kitap.all
  end

  # GET /kitaps/1
  # GET /kitaps/1.json
  def show
  end

  # GET /kitaps/new
  def new
    @kitap = Kitap.new
  end

  # GET /kitaps/1/edit
  def edit
  end

  # POST /kitaps
  # POST /kitaps.json
  def create
    @kitap = Kitap.new(kitap_params)
    @kitap.user = current_user

    respond_to do |format|
      if @kitap.save
        format.html { redirect_to @kitap, notice: 'Kitap oluşturuldu.' }
        format.json { render :show, status: :created, location: @kitap }
      else
        format.html { render :new }
        format.json { render json: @kitap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitaps/1
  # PATCH/PUT /kitaps/1.json
  def update
    respond_to do |format|
      if @kitap.update(kitap_params)
        format.html { redirect_to @kitap, notice: 'Kitap düzenlendi.' }
        format.json { render :show, status: :ok, location: @kitap }
      else
        format.html { render :edit }
        format.json { render json: @kitap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitaps/1
  # DELETE /kitaps/1.json
  def destroy
    @kitap.destroy
    respond_to do |format|
      format.html { redirect_to kitaps_url, notice: 'Kitap silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitap
      @kitap = Kitap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitap_params
      params.require(:kitap).permit(:isim, :sayfa, :ozet, :resim)
    end
end

app/controllers/yazars_controller.rb
class YazarsController < ApplicationController
  before_action :set_yazar, only: [:show, :edit, :update, :destroy]

  # GET /yazars
  # GET /yazars.json
  def index
    @yazars = Yazar.all
  end

  # GET /yazars/1
  # GET /yazars/1.json
  def show
  end

  # GET /yazars/new
  def new
    @yazar = Yazar.new
  end

  # GET /yazars/1/edit
  def edit
  end

  # POST /yazars
  # POST /yazars.json
  def create
    @yazar = Yazar.new(yazar_params)

    respond_to do |format|
      if @yazar.save
        format.html { redirect_to @yazar, notice: 'Yazar eklendi.' }
        format.json { render :show, status: :created, location: @yazar }
      else
        format.html { render :new }
        format.json { render json: @yazar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yazars/1
  # PATCH/PUT /yazars/1.json
  def update
    respond_to do |format|
      if @yazar.update(yazar_params)
        format.html { redirect_to @yazar, notice: 'Yazar düzenlendi.' }
        format.json { render :show, status: :ok, location: @yazar }
      else
        format.html { render :edit }
        format.json { render json: @yazar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yazars/1
  # DELETE /yazars/1.json
  def destroy
    @yazar.destroy
    respond_to do |format|
      format.html { redirect_to yazars_url, notice: 'Yazar silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yazar
      @yazar = Yazar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yazar_params
      params.require(:yazar).permit(:isim)
    end
end

app/controllers/yorums_controller.rb
class YorumsController < ApplicationController
  before_action :set_yorum, only: [:show, :edit, :update, :destroy]

  #eklenen kısımlar
  before_action :set_kitap, only: [:create, :destroy]
  before_action :authenticate_user!, only: [:create, :destroy]

  # GET /yorums
  # GET /yorums.json
  def index
    @yorums = Yorum.all
  end

  # GET /yorums/1
  # GET /yorums/1.json
  def show
  end

  # GET /yorums/new
  def new
    @yorum = Yorum.new
  end

  # GET /yorums/1/edit
  def edit
  end

  # POST /yorums
  # POST /yorums.json
  def create
    #@yorum = Yorum.new(yorum_params)
    
    #eklenen kısımlar
    #@yorum.kitap = @kitap    
    #@yorum.user = current_user

    @yorum = Yorum.new(yorum_params)
    @yorum.kitap = @kitap
    @yorum.user = current_user

    respond_to do |format|
      if @yorum.save
        format.html { redirect_to @kitap, notice: 'Yorum yapıldı.' }
        format.json { render :show, status: :created, location: @yorum }
      else
        format.html { render :new }
        format.json { render json: @yorum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yorums/1
  # PATCH/PUT /yorums/1.json
  def update
    respond_to do |format|
      if @yorum.update(yorum_params)
        format.html { redirect_to @yorum, notice: 'Yorum was successfully updated.' }
        format.json { render :show, status: :ok, location: @yorum }
      else
        format.html { render :edit }
        format.json { render json: @yorum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yorums/1
  # DELETE /yorums/1.json
  def destroy
    @yorum.destroy
    respond_to do |format|
      format.html { redirect_to @kitap, notice: 'Yorum silindi.' }
      format.json { head :no_content }
    end
  end

  private
    #eklenen kısımlar
    def set_kitap
      @kitap = Kitap.find(params[:kitap_id])      
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_yorum
      @yorum = Yorum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yorum_params
      params.require(:yorum).permit(:mesaj)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitaps_helper.rb
module KitapsHelper
end

app/helpers/yazars_helper.rb
module YazarsHelper
end

app/helpers/yorums_helper.rb
module YorumsHelper
end

app/views/kitaps/_form.html.erb
<%= form_with(model: kitap, local: true) do |form| %>
  <% if kitap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitap.errors.count, "error") %> prohibited this kitap from being saved:</h2>

      <ul>
      <% kitap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :resim %>
    <%= form.file_field :resim %>
  </div>

  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim %>
  </div>

  <div class="field">
    <%= form.label :sayfa %>
    <%= form.number_field :sayfa %>
  </div>

  <div class="field">
    <%= form.label :ozet %>
    <%= form.text_area :ozet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kitaps/edit.html.erb
<div class="container">
	<h1 class="text-success">Kitabı Düzenle</h1>
	<div class="card mt-3" style="background-color: #f1eee5;">
		<%= render 'form', kitap: @kitap %>
		<div>
			<%= link_to 'Göster', @kitap %>
			<%= link_to 'Geri', kitaps_path, :class => 'ml-2' %>
		</div>
	</div>
</div>

app/views/kitaps/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= link_to 'Kitap Ekle', new_kitap_path, :class => 'h3 text-success mr-3' %>
  <%= link_to 'Yazar Ekle', new_yazar_path, :class => 'h3 text-success' %>
 <div class="row">
  <% @kitaps.each do |kitap| %>
      <div class="col-lg-6">
        <div class="card my-3" style="background-color: #f1eee5;">
          <div class="row">
            <div class="col-lg-5">
                <div class="card-header h-100"><%= image_tag kitap.resim.url(:thumb) if kitap.resim? %></div>
            </div>
            <div class="col-lg-7">
              <div class="card-body">
                <%= kitap.isim %><br>
                <%= kitap.sayfa %><br>
                <%= kitap.ozet %><br>
                <%= kitap.user.email %><br><br>
                <%= link_to 'Goster', kitap %>
                <%= link_to 'Duzenle', edit_kitap_path(kitap) %>
                <%= link_to 'Sil', kitap, method: :delete, data: { confirm: 'Emin misin?' } %>  
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/kitaps/new.html.erb
<div class="container">
	<h3 class="text-success">Yeni Kitap</h3>
	<div class="card mt-2" style="background-color: #f1eee5;">
		<%= render 'form', kitap: @kitap %>
	</div>
	<%= link_to 'Geri', kitaps_path %>
</div>

app/views/kitaps/show.html.erb
<div class="container" style="background-color: #f1eee5;">
	<p id="notice"><%= notice %></p>
	<div class="card ml-5 border-0" style="background-color: #f1eee5;" >
		<p><%= image_tag @kitap.resim.url(:medium) if @kitap.resim? %></p>
	</div>

	<div class="row ml-4">
		<div class="col-lg-2 col-sm-2 col-md-2">
			<strong>Isim:</strong><br>
			<%= @kitap.isim %>
		</div>
		<div class="col-lg-1 col-sm-1 col-md-1">
			<strong>Sayfa:</strong><br>
			<%= @kitap.sayfa %>
		</div>
		<div class="col-lg-9 col-sm-9 col-md-9 mb-3">
			<strong>Ozet:</strong><br>
			<%= @kitap.ozet %>
		</div>
		<%=render 'yorums/form'%>

	</div>
	<div class="container text-center mt-3" style="height: 20%; width: 100%; background-color: #1aeee5">
		<h3>Yorumlar</h3>
	</div>
	<div class="row ml-4">
		<%@kitap.yorums.each do |c|%>
		<div class="col-md-4 col-sm-4 col-lg-4">
			<b><%=c.mesaj%></b><br/>
		</div>
		<div class="col-md-4 col-sm-4 col-lg-4"></div>			
		<div class="col-md-4 col-sm-4 col-lg-4">
			<em class="mr-4"><%=c.user.email%></em><%= link_to 'Sil', request.original_url+"/yorumlar/"+c.id.to_s, method: :delete, data: { confirm: 'Emin Misin?' } %>
		</div>
		<%end%>
		<div class="col-md-12 col-sm-12 col-lg-12">
			<%= link_to " Beğen ", kitap_like_path(@kitap), remote: :true, method: :put, :class => 'like ml-5'%>
			<%= link_to 'Düzenle', edit_kitap_path(@kitap), :class => 'ml-3' %>
			<%= link_to 'Geri', kitaps_path, :class => 'ml-3' %>
		</div>
	</div>
	

</div>
<script>
$(document).ready(function(){
  $(".like").click(function(){
    $(".like").html("Beğendin");
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uyg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top" style="background-color: #BC8F8F; color: #000000;">
  <b class="navbar-brand"><%= link_to 'Kutuphane', kitaps_path, :class => 'text-dark' %></b>
  <%= image_tag(image_path('kitap.png'), :class => "navbar-brand w" )-%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">      
        <h5>
          <%= link_to 'AnaSayfa', kitaps_path, :class => 'text-dark' %>
          <%= link_to 'Yazarlar', yazars_path, :class => 'text-dark' %>
        </h5>
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="background-color: #ffffff; color: black;">Search</button>
    </form>

    <% if user_signed_in? %>
      <strong class="text-dark"><%= current_user.email %></strong>
      <%= link_to 'Profili Duzenle', edit_user_registration_path, :class => 'navbar-link text-dark' %> 
      <%= link_to "Cikis", destroy_user_session_path, method: :delete, :class => 'navbar-link text-dark'  %>
    <% else %>
      &nbsp; <%= link_to "Kayit", new_user_registration_path, :class => 'navbar-link text-dark'  %> 
      <%= link_to "Giris", new_user_session_path, :class => 'navbar-link text-dark'  %>
    <% end %>    
  </div>
</nav>
<footer class="fixed-bottom text-center" style="background-color: #BC8F8F; color: #000000; max-width: 100%; height: 60px">
  <h5 class="text-dark mt-3">Mustafa Simsek</h5>  
</footer>

app/views/yazars/_form.html.erb
<%= form_with(model: yazar, local: true) do |form| %>
  <% if yazar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yazar.errors.count, "error") %> prohibited this yazar from being saved:</h2>

      <ul>
      <% yazar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yazars/edit.html.erb
<div class="container">
	<div class="card text-center" style="background-color: #f1eee5">
		<h1 class="text-success">Düzenlemek Yazar</h1>

		<%= render 'form', yazar: @yazar %>

		<div>
			<%= link_to 'Göster', @yazar %>
			<%= link_to 'Geri', yazars_path, :class => 'ml-3' %>
		</div>
	</div>
</div>

app/views/yazars/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
	<div class="card" style="background-color: #f1eee5">
		<h1 class="text-center text-success">Yazarlar</h1>

		<table class="ml-5">
		  <thead>
		    <tr>
		      <th><h3 class="text-success">Isim</h3></th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @yazars.each do |yazar| %>
		      <tr>
		        <td><h3><%= yazar.isim %></h3></td>
		        <h4>
		        <td><%= link_to 'Göster', yazar %></td>
		        <td><%= link_to 'Düzenle', edit_yazar_path(yazar) %></td>
		        <td><%= link_to 'Sil', yazar, method: :delete, data: { confirm: 'Emin misin?' } %></td>
		    	</h4>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

		<br>
		<div class="text-center"><h1><%= link_to 'Yazar Ekle', new_yazar_path %></h1></div>
		
	</div>
</div>

app/views/yazars/new.html.erb
<div class="container">
	<div class="card text-center	" style="background-color: #f1eee5">
		<h1 class="text-success">Yeni Yazar</h1>

		<%= render 'form', yazar: @yazar %>
		<div>
			<%= link_to 'Geri', yazars_path %>
		</div>
	</div>
</div>

app/views/yazars/show.html.erb
<div class="container">
	<div class="card text-center" style="background-color: #f1eee5">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong class="h4">Isim:</strong>
		  <h3><%= @yazar.isim %></h3>
		</p>
		<div>
			<%= link_to 'Düzenle', edit_yazar_path(@yazar) %>
			<%= link_to 'Geri', yazars_path, :class => 'ml-3' %>

		</div>
	</div>
</div>

app/views/yorums/_form.html.erb
<%= form_for ([@kitap, Yorum.new]) do |form| %>
  <div class="row">
  	<div class="col-md-6 col-lg-6 col-sm-6">
  		<%=form.text_field :mesaj,  class:"form-control" %>
	</div>
	<div class="col-md-6 col-lg-6 col-sm-6">
  		<%=form.submit "Yorum At", class:"form-action btn btn-info" %>
  	</div>
<% end %>

app/views/yorums/edit.html.erb
<h1>Editing Yorum</h1>

<%= render 'form', yorum: @yorum %>

<%= link_to 'Show', @yorum %> |
<%= link_to 'Back', yorums_path %>

app/views/yorums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Yorums</h1>

<table>
  <thead>
    <tr>
      <th>Mesaj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yorums.each do |yorum| %>
      <tr>
        <td><%= yorum.mesaj %></td>
        <td><%= link_to 'Show', yorum %></td>
        <td><%= link_to 'Edit', edit_yorum_path(yorum) %></td>
        <td><%= link_to 'Destroy', yorum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yorum', new_kitap_yorum_path %>

app/views/yorums/new.html.erb
<h1>New Yorum</h1>

<%= render 'form', yorum: @yorum %>

<%= link_to 'Back', yorums_path %>

app/views/yorums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mesaj:</strong>
  <%= @yorum.mesaj %>
</p>

<%= link_to 'Edit', edit_yorum_path(@yorum) %> |
<%= link_to 'Back', yorums_path %>